### ISSUE TITLE
Full example of writing ical file

### ISSUE THREAD

**Issue by nhaberl** [EWSoftware/PDI#12]
Hi,

would be of graet help to see a full example / tutorial how to create calendars and theier respective ical files for different mail clients / dialects

...and maybe a small helper class for creating ical files.

**Comment by EWSoftware** [comment]
The iCalendar files themselves are in a well-known format but what parts may or may not be implemented by any particular client I cannot say.  It's just not possible for me to test this with all the possible different clients and platforms out there.

The calendar browser example contains examples of how calendar files can be loaded, modified, and saved.  There's really no more to it than what that shows.

**Comment by nhaberl** [comment]
Thanks anyway, thought there are only a few
