### ISSUE TITLE
Add an Example for Recurrence.Parse Method

### ISSUE THREAD

**Issue by letscall** [EWSoftware/PDI#14]
Please add an example for Recurrence.Parse Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://ewsoftware.github.io/PDI/html/22bc1887-a035-5ee4-6e07-28f3b18e6f22.htm

**Comment by EWSoftware** [comment]
The noted topic already shows an example.  There's really not much more to it than that.  What are you looking for specifically?
