### ISSUE TITLE
Add an Example for VCard Constructor (SerializationInfo, StreamingContext)

### ISSUE THREAD

**Issue by manferpon** [EWSoftware/PDI#15]
Please add an example for VCard Constructor (SerializationInfo, StreamingContext).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://ewsoftware.github.io/PDI/html/3ca6e208-8893-a998-78a0-288fef4cf1fa.htm

**Comment by EWSoftware** [comment]
There's really no meaningful use case that I can provide.  Unless you're deriving a class from VCard, you probably don't even need to know about this or use it.  If you are, just retrieve the values you want in the constructor and add the values you want in the `GetObjectData` override.  I suggest looking at the [ISerializable interface](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.iserializable?view=netcore-3.1) docs as that's really all this is and the example there tells you all you need to know.
