### ISSUE TITLE
Add an Example for ISO8601Format.BasicDateTimeUniversal Field

### ISSUE THREAD

**Issue by gargirani** [EWSoftware/PDI#16]
Please add an example for ISO8601Format.BasicDateTimeUniversal Field.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://ewsoftware.github.io/PDI/html/f66e2206-d269-e595-02e6-865a3fe0caeb.htm

**Comment by EWSoftware** [comment]
This is just a constant.  You'd just [use it in place of a literal string](https://github.com/EWSoftware/PDI/blob/master/Source/CSharpDemos/PDIWinFormsTest/EventRecurTestForm.cs#L85) if you really need it.
