### ISSUE TITLE
Setting the By... properties of a Recurrence after initialisation

### ISSUE THREAD

**Issue by micycle1** [EWSoftware/PDI#18]
Is it possible to set the By.. (e.g. `ByHour`, `ByMinute`) of a `Recurrence` once it's initialised?

The doc even says "used to modify the rule" but I can only see the getters for these members -- what about setters for them?
![image](https://user-images.githubusercontent.com/9304234/113012260-82b2fe80-9172-11eb-82f9-f996ffb4070a.png)

The only way I can find right now to set these at all is in the via RRule string at initialisation, e.g: `new Recurrence(RRULE:FREQ=WEEKLY;COUNT=30;INTERVAL=1;WKST=MO;BYHOUR=8,9;BYMINUTE=5);`

**Comment by EWSoftware** [comment]
They are [collection instances](http://ewsoftware.github.io/PDI/html/89035826-7d0d-9605-bf90-59162a43efd6.htm).  You can add/remove entries as needed.  You can also clear them and add a new range of new entries.  Each property's documentation shows an example of using AddRange ([ByDay](http://ewsoftware.github.io/PDI/html/e5b0c831-273a-5163-05b2-f15a040030d8.htm))

**Comment by micycle1** [comment]
Timely response. Thanks.
