### ISSUE TITLE
Add an Example for Recurrence Class

### ISSUE THREAD

**Issue by ghost** [EWSoftware/PDI#24]
Please add an example for Recurrence Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://ewsoftware.github.io/PDI/html/e24c178a-122b-5a60-3c03-f14fbbddd52f.htm

**Comment by EWSoftware** [comment]
Most of the properties have examples and there are some general topics on usage.  Can you be more specific about what you are looking for regarding an example?
